### ISSUE TITLE
Updatable's ActiveStorage implementation broadcasts to multiple/wrong keys

### ISSUE THREAD

**Issue by julianrubisch** [stimulusreflex/cable_ready#201]
This issue emerged when I was first trying to integrate `has_one_attached` in the same way we have `has_many_attached`. I added `has_one_attached` to `Updatable` like so:

```rb
      def has_one_attached(name, **options)
        option = options.delete(:enable_updates)
        broadcast = option.present?
        result = super
        enrich_attachments_with_updates(name, option) if broadcast
        result
      end
```

After I wired up the `User` model:

```rb
class User < ApplicationRecord
  # ...
  has_one_attached :avatar, enable_updates: true
end
```

I got the following test failure from :

```
unexpected invocation: #<Mock:server>.broadcast("gid://dummy/Dugong/1:avatar", {:changed => ["id", "name", "record_type", "record_id", "blob_id", "created_at"]})
```

which is wrong simply because `Dugong` **has no** `avatar` AS association.

cc @andrewerlanger

**Comment by julianrubisch** [comment]
my guess is that due to the polymorphic nature of the `ActiveStorage::Attachment` association, simply all `record_types` are pinged?

**Comment by andrewerlanger** [comment]
@julianrubisch I think the problem here is that `broadcast_for!(model, operation)` (over [here](https://github.com/stimulusreflex/cable_ready/blob/aab58aac789cab06a0789bc4b028d9df47b910fb/app/models/concerns/cable_ready/updatable/collections_registry.rb#L12)) is being called on the `ActiveStorage::Attachment` class, which has two registered collections here.

Specifically, we have (in the dummy app):

```rb
# user.rb
has_one_attached :avatar, enable_updates: true

# dugong.rb
has_many_attached :images, enable_updates: true
```

This means that `@registered_collections` ends up looking something like the following for the `ActiveStorage::Attachment` class:

```rb
[{klass: User, name: :avatar, ...}, {klass: Dugong, name: :images, ...}]
```

When attached an avatar to a user, for example, we then iterate through these `@registered_collections` and run the [following line](https://github.com/stimulusreflex/cable_ready/blob/aab58aac789cab06a0789bc4b028d9df47b910fb/app/models/concerns/cable_ready/updatable/collections_registry.rb#L18) for each of them:

```rb
collection[:klass].cable_ready_update_collection(resource, collection[:name], model)
```

**Comment by julianrubisch** [comment]
Interesting! We could give this a try, yes!

**Comment by andrewerlanger** [comment]
Awesome :)

One thing to double-check here, although I think we should be okay, is that this doesn't have an unintended side effects for how we handle non-ActiveStorage collections (e.g. `user.posts`).

**Comment by julianrubisch** [comment]
Yeah it boils down on having good tests. I think I have a branch lying around somewhere, I'll take a look!

**Comment by leastbad** [comment]
I just wanted to follow up and ask if anything came of this investigation?

Otherwise, I'm going to close this ticket soon, okay?
