### ISSUE TITLE
dom_id is not consistent with Rails

### ISSUE THREAD

**Issue by synth** [stimulusreflex/cable_ready#287]
First, TY for SR and CR! I'm new here, so pardon if this has been discussed at length already. 

In short, I have noticed that CR's `dom_id` implementation deviates significantly from Rails. It adds the "#" prefix and downcases the identifier. The reason why this is important (IMO), is that I am using `dom_id` for a channel identifier and thus makes usage of `dom_id` in a reflex that sends a message to a channel via CR incompatible. 

Here is an example: 

```ruby
class MyRoomChannel < ApplicationCable::Chanell
  def subscribed
    stream_from (dom_id(my_model) << "_messages")
  end
end

class MyMessageReflex < ApplicationReflex
  def update
    model_instance = element.signed[:secure]
    channel = dom_id(model_instance) << "_messages"
    cable_ready[channel].console_log(message: "reflex update message").broadcast
  end
end 
```

This seems like it should work, but doesn't. It actually doesn't work in my case for 2 reasons: 
1. A hash prefix is added to the dom_id
2. Also the dom_id is downcased which breaks for me because I'm using hashids which are mixed casing.

**Comment by marcoroth** [comment]
Hey @synth, thanks for opening this issue!

The CableReady `dom_id` is adding a `#` by design. The reason for this is because you are usually using the `dom_id` from ActionView in actual view files, whereas the CableReady one is primarily meant to be used in reflexes to generate a valid CSS selector for reflex morphs or for constructing the selector for a CableReady operation.

Because you don't need a `#` when using it in views for the `id` attribute on elements but need one for targeting such an elment in a Reflex we automatically add the `#` for you, so you don't have to interpolate it yourself all the time.

Now, while the `#` is added by default, I'm wondering if we should provide a keyword argument option to disable the addition of the `#`.

As for the downcasing, I'm not sure if that actually really makes sense as we have it right now and wondering if we should just remove the `.downcase` call in the method. I agree that this one is kinda unexpected.

**Comment by synth** [comment]
Thanks for the explanation.  I'm realizing that if we want ActiveRecord's implementation, we can just call it :) So, we can go ahead and close this. Cheers!

**Comment by marcoroth** [comment]
Oh yeah right, that also works! But it might still be good to have the CableReady as close as possible to the Rails one.

**Comment by synth** [comment]
Maybe an argument like `selector: true`? This way you don't break existing usages and also allows people to turn it off to get more AR like behavior? Just a thought.
